[config]
schemaVersion = "0.0.1"

[package]
namespace = "crazy_MT2"
name = "Silk_Song_Clan"
versionNumber = "0.2.2"
description = "Hollow Knight Silksong Mod for Monster Train 2"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2304"
MT2-Trainworks_Reloaded = "0.6.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


